### ISSUE TITLE
Modificar diagrama E-R

### ISSUE THREAD

**Issue by DaniFdezC** [ManPuyol/Jean-Monnet-Serious-Game#14]
- [x] Añadir al diagrama la nueva tabla user_achievements
- [x] Añadir al diagrama la nueva tabla user_subjects
- [x] Añadir tema al quiz en lugar de quiz_details

**Comment by DaniFdezC** [comment]
- [ ] Añadir al schema la tabla user_achievements
- [ ] Añadir al schema la tabla user_subject
- [ ] Cambiar los schemas para tener el unit en quizzes en lugar de quiz_details

**Comment by DaniFdezC** [comment]
Modificado lo necesario, a espera de la issue #18 para poder continuar

**Comment by mmasias** [comment]
te acabo de contestar
-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by mmasias** [comment]
Perdón! No le habia dado al enviar 🥴🥴🥴🥴🥴🥴🥴🥴
-
Manuel Masías
http://es.linkedin.com/in/mmasias
