### ISSUE TITLE
Preguntas para Manuel

### ISSUE THREAD

**Issue by DaniFdezC** [ManPuyol/Jean-Monnet-Serious-Game#18]
En el diagrama entidad relación, la tabla "users" tienen 2 tipos de roles, "student" o "teacher".

La relación entre las distintas tablas cambia dependiendo de este rol, ¿deberíamos hacer 2 tipos de diagrama E-R?

Uno en el que sea users(students), y las relaciones sean de unlocks achievements, takes subjects.... y otra que sea de users(teachers) y las relaciones sean de creates subjects, creates unit

**Comment by mmasias** [comment]
No, no se suelen crear dos: uno deberia ser suficiente. Me explico (pensando en voz alta):

Para que un USERS "take ACHIEVEMENTS" debe ser alumno. Para que un USER cree SUBJECTS debe ser profesor. Probablemente que detectes lo que mencionas sea señal que hacen falta entidades. Un STUDENT es un USER con rol. Un TEACHER es un USER también. Asi tendrías USER relacionado con STUDENT y con TEACHER mediante la relacion "puede ser un..." y con eso dejas resueltas las relaciones que vienen a continuación. Y ganas algo adicional: puedes tener alguien que sea STUDENT y TEACHER sin duplicar su USER

**Comment by DaniFdezC** [comment]
Entonces una aproximación más concreta a lo que queremos sería dos tablas para los usuarios, es decir, así ? :


```mermaid
erDiagram 
    LANGUAGE {
        int id
        string language
    }
    STUDENTS {
        varchar id PK
        string full_name
        string email
        date created_at
        date updated_at
    }     
    TEACHERS {
        varchar id PK
        string full_name
        string email
        date created_at
        date updated_at
    }  
    ACHIEVEMENTS {
        int id PK
        string name
        string description
        date created_at
        date updated_at
    }
    SUBJECTS {
        int id PK
        string name
        string description
        boolean active
        date created_at
        date updated_at
    }
    UNITS {
        int id PK
        int subject_id FK
        string name
        boolean active
        smallint questions_per_quiz
        date created_at
        date updated_at
    }
    QUESTIONS {
        int id PK
        int unit_id FK
        string question
        boolean hard
        boolean active
        date created_at
        date updated_at
    }
    ANSWERS {
        int id PK
        int question_id PK
        string answer
        boolean correct
        date created_at
        date updated_at
    }
    QUIZZES {
        int id PK
        int user_id FK
        int unit_id FK
        smallint score
        varchar meta "Correct answer"
        date created_at
        date updated_at
    }
    QUIZ_DETAILS {
        int id PK
        int quiz_id FK
        int user_id FK
        int question_id FK
        boolean correct
        date created_at
    }

    STUDENTS }|--|{ ACHIEVEMENTS : obtains
    STUDENTS }|--|{ SUBJECTS : takes
    STUDENTS }|--|{ UNITS : unlocks
    STUDENTS ||--|{ QUIZZES : takes

    TEACHERS }|--|{ SUBJECTS : create
    TEACHERS }|--|{ UNITS : create
    TEACHERS ||--|{ ANSWERS : create

    QUIZZES }|--|| UNITS : contains
    QUIZZES ||--|{ QUIZ_DETAILS : contains
    QUIZ_DETAILS ||--|| STUDENTS : belongs
    QUIZ_DETAILS ||--|| QUESTIONS : contains
    QUIZ_DETAILS ||--|| ANSWERS : contains

    SUBJECTS ||--|{ UNITS : contains
    UNITS ||--|{ QUESTIONS : contains
    QUESTIONS ||--|{ ANSWERS : contains

    
```

**Comment by mmasias** [comment]
user {id, nombre, etc...}
teachers {id, id_user, camposEspecificos}
students {id, id_user, camposEspecificos}

**Comment by DaniFdezC** [comment]
Todos tendrían los mismos campos, salvo el rol que está en "users", el cual si hacemos de esta forma no le necesitaríamos, actualmente lo que estamos guardando en la BBDD es esto:
![users](https://github.com/ManPuyol/Jean-Monnet-Serious-Game/assets/102489316/2686436f-d786-40b6-9428-7253b439aefd)

**Comment by mmasias** [comment]
Nontiendo...

**Comment by DaniFdezC** [comment]
Si utilizamos el enfoque de :

>user {id, nombre, etc...}
>teachers {id, id_user, camposEspecificos}
>students {id, id_user, camposEspecificos}

Realmente los teachers y students no tienen campos específicos, por lo que nos quedaría la base de datos de la siguiente forma

>user {id, email, full_name}
>teacher {id, id_user}
>student {id, id_user}

A la hora de hacer el DER quedaría más bonito, ya que tienes una tabla más y las relaciones se ven más claras, pero a nivel de base de datos/aplicación qué extras nos podría aportar?

Ahora como lo tenemos planificado y queries hechas es que dependiendo del valor del "rol" de ese usuario, mostramos un dashboard/datos u otros; separándolo en 3 tablas (user + teacher + students), sería lo mismo sólo que tendríamos que buscarlo en la tabla correspondiente (teacher, student)

**Comment by mmasias** [comment]
Exacto: teacher y student son tablas de roles. El enfoque no es tanto que se vea bonito el der: es que modela mejor la realidad, es más escalable, etc. Si un teacher tiene un descriptor de profesor agregarías ese campo a la tabla teachers y no hay conflicto con student para el mismo usuario. Además, de ese modo las consultas te quedan mejor auto-descritas (SELECT xyz FROM teacher.... es más clara que SELECT xyz FROM users WHERE role=1)

**Comment by DaniFdezC** [comment]
Entonces la relación final sería: 
![image](https://github.com/ManPuyol/Jean-Monnet-Serious-Game/assets/102489316/5d6559e7-fa92-4ba0-8a62-e4481cdd19b2)

**Comment by mmasias** [comment]
Si está resuelta la duda, cerrar el issue y dejarme ser feliz 😛
