### ISSUE TITLE
📝@GoogleDocs

### ISSUE THREAD

**Issue by mmasias** [ManPuyol/Jean-Monnet-Serious-Game#58]
Aquí estarán las [preguntas](https://docs.google.com/spreadsheets/d/18K_VjExv0JO7n3kJceD-eu3GUYoueMNBfS6Wj0alEPE/edit?usp=sharing) para la plataforma.

**Comment by mmasias** [comment]
Y aquí está el prompt de [ChatGPT](https://chatgpt.com/share/bcc45227-a4a0-4927-b834-fee86e6cb86d)

**Comment by DaniFdezC** [comment]
Están todas las preguntas guardadas en la asignatura correspondiente.
