### ISSUE TITLE
Revision de TFG

### ISSUE THREAD

**Issue by ManPuyol** [ManPuyol/Jean-Monnet-Serious-Game#62]
Buen día, 

He terminado la redacción lo único que me falta es agregar el índice de imágenes. Espero su visto bueno para imprimir el TFG.

Enlace al documento:

https://docs.google.com/document/d/19OrwmpWpdFExWvykzlVLNsiSkEGgvx7h/edit?pli=1

Gracias por su atención

**Comment by mmasias** [comment]
Resta además ajustar (o suprimir) la sección de agradecimientos.

**Comment by ManPuyol** [comment]
Perfecto! Ya esta agregado todo y subido al campus.
