### ISSUE TITLE
Diagrama entidad relacion

### ISSUE THREAD

**Issue by ManPuyol** [ManPuyol/Jean-Monnet-Serious-Game#7]
Crear Diagrama de entidad relacion en la WIki

**Comment by ManPuyol** [comment]
Trabajando en ello en  la [wiki](https://github.com/ManPuyol/Jean-Monnet-Serious-Game/wiki/Diagramas#diagrama-entidad-relacion) 📖

**Comment by mmasias** [comment]
`PREGUNTAS.pregunta_ID` creo que es `RESPUESTAS.pregunta_ID`

Pregunta: a `RESPUESTAS` no le faltaría `RESPUESTAS.correcta`?

Propuestas:

- Agregaría el campo `*.activo` para poder deshabilitar rápidamente un elemento.
- Agregaría ya la capacidad de almacenar los recursos en  múltiples idiomas. Una tabla de RECURSOS que sería algo así como {id, idIdioma, stringRecurso}, luego una tabla de idiomas {id, nombreIdioma} y en los campos en los que haya texto, elegido el idioma (que por defecto podría ser español, con id=1), creamos la entrada en RECURSOS, pillamos el id recién creado y lo guardamos dónde corresponda.

**Comment by ManPuyol** [comment]
Se agregaron `cuestionarios`, `detalle_cuestionario` , `recursos`  e `idiomas` al DER
